<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
		<RootNamespace>MudBlazor.SampleApp</RootNamespace>
	</PropertyGroup>


	<ItemGroup>
		<ProjectReference Include="..\MudBlazor.SampleApp.Client\MudBlazor.SampleApp.Client.csproj" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.*" />
	</ItemGroup>

</Project>